import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from 'react'
import {saveAs}  from 'file-saver'
import axios, { AxiosResponse } from 'axios'


const Home: NextPage = () => {
  //テスト１：Djangoから「1」というデータを取得するテスト用
  const [data, setData] = useState("first");
  var title_state = false;

  async function useOperate(){
    title_state = !title_state;
    if(title_state){
      document.title =`title state true`
    }else{
      document.title =`title state false`
    }
    const res = await fetch('/api/test_code');
    const res_headers = await res.headers;
    const res_data = await res_headers.get('mydata');
    if(res_data == null){
      setData("");
    }else{
      setData(res_data);
    }
    const res_content_type = await res_headers.get('CONTENT_TYPE');
    if(res_content_type !=null){
      if(title_state){
        document.title = res_content_type;
      }else{
        document.title = res_content_type + false;
      }
    }else{
      document.title = "null!";
    }
  }
  //テスト２：Djangoからcsvデータを取得するテスト用
  async function Operate(){
    axios.get('/api/operate', {responseType: 'blob',})
      .then((res: AxiosResponse) => {
        const blob = new Blob([res.data], {type: res.data.type});
        const fileName = getFileName(res.headers['content-disposition']);
        saveAs(blob, fileName);
      });
  }

  const getFileName = (contentDisposition: string) => {
    return decodeURI(contentDisposition).substring(
      contentDisposition.indexOf('filename=') + 10,//length of "filename=_"
      contentDisposition.length - 1,
    )
  };
  //テスト３：Next.jsからcsvファイルを送信するテスト用
  const [file, setFile] = useState<File| null>(null);
  const handleFileImportChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if(e.target.files) setFile(e.target.files[0])
  };
  const handleSubmit = () => {
    let formData = new FormData();
    if(file){
      formData.append('csv_file', file);
      axios.defaults.xsrfCookieName = 'csrftoken';
      axios.defaults.xsrfHeaderName = "X-CSRFTOKEN";
      axios.post('/api/upload_operate', formData)
      .then((res: AxiosResponse) => {
        const blob = new Blob([res.data], {type: res.data.type});
        const fileName = getFileName(res.headers['content-disposition']);
        saveAs(blob, fileName);
      });
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>I'm here!!!!!!!!!</h1>

        <h1>＜＜テスト１：Djangoから「1」というデータを取得するテスト用＞＞</h1>
        <h1>{ data }</h1>
        <button onClick={useOperate}>data変更</button>
        <h1>{ String(title_state) }</h1>

        <h1>＜＜テスト２：Djangoからcsvデータを取得するテスト用＞＞</h1>
        <button onClick={Operate}>operate用テストボタン</button>

        <h1>＜＜テスト３：Next.jsからcsvファイルを送信するテスト用＞＞</h1>
        {/* {% csrf_token %} */}
        <input type='file' onChange={handleFileImportChange} />
        <button onClick={handleSubmit}>送信する</button>

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export default Home
